#!/usr/bin/env python

from __future__ import print_function
import sys
import os
import os.path
import re
import subprocess
import argparse
import time

WAIT_TIME=3

'''
- This directory has to be put under /davidlazar;
- Fix the GOPATH if necessary.
'''

def setup():
    cmd("go get ./...") 
    cmd("go install ./vuvuzela-client ./vuvuzela-entry-server ./vuvuzela-server")
    cmd("cp -r ./confs $GOPATH/bin")

def start():
    GOPATH=os.environ['GOPATH']
    os.chdir(GOPATH + '/bin')

    print("--> starting the last server..")
    cmd("screen -d -m -S last ./vuvuzela-server -conf confs/local-last.conf")
    time.sleep(WAIT_TIME)

    print("--> starting the middle server..")
    cmd("screen -d -m -S middle ./vuvuzela-server -conf confs/local-middle.conf")
    time.sleep(WAIT_TIME)

    print("--> starting the first server..")
    cmd("screen -d -m -S first ./vuvuzela-server -conf confs/local-first.conf")
    time.sleep(WAIT_TIME)

    print("--> starting the entry server..")
    cmd("screen -d -m -S entry ./vuvuzela-entry-server -wait 1s")
    time.sleep(WAIT_TIME)

    print("--> starting the client alice..")
    cmd("screen -d -m -S alice ./vuvuzela-client -conf confs/alice.conf")

    print(cmd_out("screen -list"))
    print("Done")

def kill():
    cmd("pkill screen")

def cmd(cmd, quiet=False):
    if quiet:
        proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=True)
    else:
        proc = subprocess.Popen(cmd, shell=True)

    out, _ = proc.communicate()

    if proc.returncode:
        if quiet:
            print('Log:\n', out, file=sys.stderr)
        print('Error has occured running command: %s' % cmd, file=sys.stderr)
        sys.exit(proc.returncode)

def cmd_out(cmd):
    proc = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)

    out, _ = proc.communicate()

    if proc.returncode:
        print('Error occured running host command: %s' % cmd, file=sys.stderr)
        sys.exit(proc.returncode)

    return out


def print_usage(parser):
    parser.print_help(file=sys.stderr)
    sys.exit(2)

def main():
    parser = argparse.ArgumentParser(description='Template cmd wrapper.')
    cmds = {
            'setup': setup,
            'start': start,
            'kill' : kill,
            'help': lambda: print_usage(parser),
            }

    for name in cmds.keys():
        if '_' in name:
            cmds[name.replace('_','-')] = cmds[name]

    cmdlist = sorted(cmds.keys())

    parser.add_argument(
        'action',
        metavar='action',
        nargs='?',
        default='help',
        choices=cmdlist,
        help='Action is one of ' + ', '.join(cmdlist))

    parser.add_argument('-v', '--verbose', action='store_true', help='enable verbose')

    args = parser.parse_args()

    if args.verbose:
        os.environ['V'] = '1'

    cmds[args.action]()


if __name__ == '__main__':
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit('\nInterrupted')
